[project]
name = "medgemma-audit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jvrbntz", email = "javierbenitezmd@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "kagglehub>=1.0.2",
    "pandas>=3.0.5",
]

[project.scripts]
medgemma-audit = "medgemma_audit:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
